import jsPDF from 'jspdf';

/**
 * Générer un PDF d'analyse de tarifs
 */
export function generateRateAnalysisPDF({ results, formData, language = 'fr' }) {
  const translations = {
    fr: {
      title: 'Analyse de Tarifs Personnalisée',
      subtitle: 'PricingPro - Votre calculateur de tarifs intelligent',
      date: 'Date',
      profile: 'Votre Profil',
      profession: 'Profession',
      location: 'Localisation',
      experience: 'Années d\'expérience',
      experienceLevel: 'Niveau d\'expérience',
      skills: 'Compétences',
      junior: 'Junior',
      mid: 'Confirmé',
      senior: 'Senior',
      results: 'Vos Tarifs Recommandés',
      hourly: 'Tarif Horaire',
      daily: 'Tarif Journalier',
      monthly: 'Tarif Mensuel',
      market: 'Comparaison Marché',
      marketMin: 'Minimum Marché',
      marketAvg: 'Moyenne Marché',
      marketMax: 'Maximum Marché',
      yourRate: 'Votre Tarif',
      breakdown: 'Détail du Calcul',
      baseRate: 'Tarif de base',
      experienceBonus: 'Prime d\'expérience',
      skillsBonus: 'Prime compétences',
      locationAdjustment: 'Ajustement géographique',
      total: 'Total recommandé',
      advice: 'Nos Conseils',
      adviceText: 'Vos tarifs sont compétitifs ! Continuez à développer vos compétences et votre expertise pour augmenter votre valeur sur le marché.',
      footer: 'Ce rapport a été généré par PricingPro - https://pricingpro-mauve.vercel.app',
      dataSource: 'Données basées sur',
      realData: 'tarifs réels du marché'
    },
    en: {
      title: 'Personalized Rate Analysis',
      subtitle: 'PricingPro - Your smart pricing calculator',
      date: 'Date',
      profile: 'Your Profile',
      profession: 'Profession',
      location: 'Location',
      experience: 'Years of experience',
      experienceLevel: 'Experience level',
      skills: 'Skills',
      junior: 'Junior',
      mid: 'Mid-level',
      senior: 'Senior',
      results: 'Your Recommended Rates',
      hourly: 'Hourly Rate',
      daily: 'Daily Rate',
      monthly: 'Monthly Rate',
      market: 'Market Comparison',
      marketMin: 'Market Minimum',
      marketAvg: 'Market Average',
      marketMax: 'Market Maximum',
      yourRate: 'Your Rate',
      breakdown: 'Rate Breakdown',
      baseRate: 'Base rate',
      experienceBonus: 'Experience bonus',
      skillsBonus: 'Skills bonus',
      locationAdjustment: 'Location adjustment',
      total: 'Recommended total',
      advice: 'Our Advice',
      adviceText: 'Your rates are competitive! Keep developing your skills and expertise to increase your market value.',
      footer: 'This report was generated by PricingPro - https://pricingpro-mauve.vercel.app',
      dataSource: 'Data based on',
      realData: 'real market rates'
    }
  };

  const t = translations[language];

  // Créer le PDF
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Couleurs
  const primaryColor = [147, 51, 234]; // Purple
  const secondaryColor = [236, 72, 153]; // Pink
  const darkGray = [31, 41, 55];
  const lightGray = [156, 163, 175];
  const bgGray = [249, 250, 251];

  // === HEADER ===
  // Fond dégradé (simulé avec un rectangle)
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 60, 'F');

  // Logo et titre
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('📊 PricingPro', pageWidth / 2, 25, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(t.title, pageWidth / 2, 40, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.text(`${t.date}: ${new Date().toLocaleDateString(language === 'fr' ? 'fr-FR' : 'en-US')}`, pageWidth / 2, 50, { align: 'center' });

  yPosition = 70;

  // === SECTION: PROFIL ===
  doc.setFillColor(...bgGray);
  doc.rect(15, yPosition, pageWidth - 30, 60, 'F');

  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(t.profile, 20, yPosition + 10);

  doc.setFontSize(10);
  doc.setTextColor(...darkGray);
  doc.setFont('helvetica', 'normal');

  const profileData = [
    `${t.profession}: ${formData.profession || 'N/A'}`,
    `${t.location}: ${formData.location || 'N/A'}`,
    `${t.experienceLevel}: ${t[formData.experienceLevel] || formData.experienceLevel || 'N/A'}`,
    `${t.experience}: ${formData.experience || 0} ${language === 'fr' ? 'ans' : 'years'}`,
    `${t.skills}: ${formData.skills && formData.skills.length > 0 ? formData.skills.join(', ') : 'N/A'}`
  ];

  let profileY = yPosition + 20;
  profileData.forEach((line, idx) => {
    doc.text(line, 20, profileY + (idx * 8));
  });

  yPosition += 70;

  // === SECTION: TARIFS RECOMMANDÉS ===
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(t.results, 20, yPosition);

  yPosition += 10;

  // Cartes de tarifs
  const rateBoxWidth = (pageWidth - 45) / 3;
  const rateBoxHeight = 35;

  // Tarif horaire
  doc.setFillColor(240, 240, 255);
  doc.rect(15, yPosition, rateBoxWidth, rateBoxHeight, 'F');
  doc.setDrawColor(...primaryColor);
  doc.rect(15, yPosition, rateBoxWidth, rateBoxHeight);

  doc.setFontSize(9);
  doc.setTextColor(...lightGray);
  doc.setFont('helvetica', 'normal');
  doc.text(t.hourly, 15 + rateBoxWidth / 2, yPosition + 10, { align: 'center' });

  doc.setFontSize(20);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`${results.hourly}€`, 15 + rateBoxWidth / 2, yPosition + 25, { align: 'center' });

  // Tarif journalier (mis en valeur)
  doc.setFillColor(...primaryColor);
  doc.rect(20 + rateBoxWidth, yPosition, rateBoxWidth, rateBoxHeight, 'F');

  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.text(t.daily, 20 + rateBoxWidth + rateBoxWidth / 2, yPosition + 10, { align: 'center' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`${results.daily}€`, 20 + rateBoxWidth + rateBoxWidth / 2, yPosition + 25, { align: 'center' });

  // Tarif mensuel
  doc.setFillColor(240, 240, 255);
  doc.rect(25 + 2 * rateBoxWidth, yPosition, rateBoxWidth, rateBoxHeight, 'F');
  doc.setDrawColor(...primaryColor);
  doc.rect(25 + 2 * rateBoxWidth, yPosition, rateBoxWidth, rateBoxHeight);

  doc.setFontSize(9);
  doc.setTextColor(...lightGray);
  doc.setFont('helvetica', 'normal');
  doc.text(t.monthly, 25 + 2 * rateBoxWidth + rateBoxWidth / 2, yPosition + 10, { align: 'center' });

  doc.setFontSize(18);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`${results.monthly.toLocaleString()}€`, 25 + 2 * rateBoxWidth + rateBoxWidth / 2, yPosition + 25, { align: 'center' });

  yPosition += 50;

  // === SECTION: COMPARAISON MARCHÉ ===
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(t.market, 20, yPosition);

  yPosition += 10;

  doc.setFillColor(...bgGray);
  doc.rect(15, yPosition, pageWidth - 30, 45, 'F');

  doc.setFontSize(10);
  doc.setTextColor(...darkGray);
  doc.setFont('helvetica', 'normal');

  const marketData = [
    { label: t.marketMin, value: `${results.market.min}€/j`, color: [239, 68, 68] },
    { label: t.marketAvg, value: `${results.market.avg}€/j`, color: [234, 179, 8] },
    { label: t.yourRate, value: `${results.daily}€/j`, color: primaryColor },
    { label: t.marketMax, value: `${results.market.max}€/j`, color: [34, 197, 94] }
  ];

  let marketY = yPosition + 10;
  marketData.forEach((item, idx) => {
    doc.setTextColor(...darkGray);
    doc.text(item.label, 20, marketY);
    doc.setTextColor(...item.color);
    doc.setFont('helvetica', 'bold');
    doc.text(item.value, pageWidth - 25, marketY, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    marketY += 10;
  });

  yPosition += 55;

  // === SECTION: DÉTAIL DU CALCUL ===
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(t.breakdown, 20, yPosition);

  yPosition += 10;

  doc.setFillColor(...bgGray);
  const breakdownHeight = results.breakdown.location !== 0 ? 50 : 40;
  doc.rect(15, yPosition, pageWidth - 30, breakdownHeight, 'F');

  doc.setFontSize(10);
  doc.setTextColor(...darkGray);
  doc.setFont('helvetica', 'normal');

  const breakdownData = [
    { label: t.baseRate, value: `${results.breakdown.base}€` },
    { label: t.experienceBonus, value: `+${results.breakdown.experience}€` },
    { label: t.skillsBonus, value: `+${results.breakdown.skills}€` }
  ];

  if (results.breakdown.location !== 0) {
    breakdownData.push({
      label: t.locationAdjustment,
      value: `${results.breakdown.location >= 0 ? '+' : ''}${results.breakdown.location}€`
    });
  }

  let breakdownY = yPosition + 10;
  breakdownData.forEach((item) => {
    doc.text(item.label, 20, breakdownY);
    doc.text(item.value, pageWidth - 25, breakdownY, { align: 'right' });
    breakdownY += 10;
  });

  // Ligne de séparation
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, breakdownY + 2, pageWidth - 20, breakdownY + 2);

  // Total
  breakdownY += 8;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text(t.total, 20, breakdownY);
  doc.text(`${results.daily}€/jour`, pageWidth - 25, breakdownY, { align: 'right' });

  yPosition += breakdownHeight + 10;

  // === SECTION: CONSEILS ===
  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`💡 ${t.advice}`, 20, yPosition);

  yPosition += 10;

  doc.setFillColor(254, 243, 199);
  doc.rect(15, yPosition, pageWidth - 30, 25, 'F');
  doc.setDrawColor(245, 158, 11);
  doc.setLineWidth(2);
  doc.line(15, yPosition, 15, yPosition + 25);

  doc.setFontSize(10);
  doc.setTextColor(...darkGray);
  doc.setFont('helvetica', 'normal');
  const adviceLines = doc.splitTextToSize(t.adviceText, pageWidth - 40);
  doc.text(adviceLines, 20, yPosition + 8);

  yPosition += 35;

  // Data source badge
  if (results.dataSource === 'real' && results.sourceCount) {
    doc.setFontSize(9);
    doc.setTextColor(...lightGray);
    doc.setFont('helvetica', 'italic');
    doc.text(`✅ ${t.dataSource} ${results.sourceCount} ${t.realData}`, 20, yPosition);
  }

  // === FOOTER ===
  doc.setFontSize(8);
  doc.setTextColor(...lightGray);
  doc.setFont('helvetica', 'normal');
  doc.text(t.footer, pageWidth / 2, pageHeight - 15, { align: 'center' });

  // Télécharger le PDF
  const fileName = `PricingPro_Analysis_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}